CREATE DATABASE AddressBookSystem;
SHOW DATABASES;
CREATE TABLE contacts
( FirstName VARCHAR(50) NOT NULL PRIMARY KEY,
LastName VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
Zip INT(30) NOT NULL,
PhoneNumber INT(30) NOT NULL,
Email VARCHAR(50) NOT NULL );
SHOW TABLES;